# Generated by Django 5.2 on 2025-04-17 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="Название курса")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="materials/image", verbose_name="Изображение курса"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание курса")),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="Название урока")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="materials/image", verbose_name="Изображение урока"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание урока")),
                ("video_url", models.URLField(blank=True, null=True, verbose_name="Ссылка на видео")),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="materials.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
    ]
