# Generated by Django 5.2 on 2025-05-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_update",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновление курса"),
        ),
    ]
